#ifndef CAPYCITY_BUILDINGTYPE_H
#define CAPYCITY_BUILDINGTYPE_H

enum BuildingType : char {
    EMPTY = 'E',
    WATER_ENERGY_PLANT = 'W',
    SOLAR_ENERGY_PLANT = 'S',
    WIND_ENERGY_PLANT = 'I',
};

#endif //CAPYCITY_BUILDINGTYPE_H